### ISSUE TITLE
21.11 does not find the reserve id correctly

### ISSUE THREAD

**Issue by kidclamp** [bywatersolutions/koha-plugin-item-recalls#11]
let reserve_elt = $('table tr:nth-child(2) td:nth-child(1) input[name="reserve_id"]')
    let reserve_id = reserve_elt.val();

Above code needs to be  adjusted

**Comment by kylemhall** [comment]
@kidclamp you are referring to this? https://github.com/bywatersolutions/koha-plugin-item-recalls/blob/master/Koha/Plugin/Com/ByWaterSolutions/ItemRecalls/intranetuserjs.tt#L4

**Comment by kidclamp** [comment]
yes
