### ISSUE TITLE
manualinvoice is deprecated, must use Koha::Account->add_debit

### ISSUE THREAD

**Issue by kidclamp** [bywatersolutions/koha-plugin-item-recalls#2]

**Comment by kylemhall** [comment]
The plugin should be able to handle both cases: https://github.com/bywatersolutions/koha-plugin-item-recalls/blob/master/Koha/Plugin/Com/ByWaterSolutions/ItemRecalls.pm#L418

Is the plugin up to date?

**Comment by kidclamp** [comment]
I misread a 5 as a 6 :-)
